---
- name:
  hosts: all
  become_user: root
  tasks:
    - name: Installing epel-realse
      yum:
        name: epel-release
        state: latest

    - name: Installing Ansible
      yum:
        name: ansible
        state: latest 
 
