---
- hosts: all
  become_user: root
  tasks:

  - name: Install epel-release
    yum:
      name: epel-release
      state: latest

  - name: Installing latest version of Apache
    yum:
      name: httpd
      state: latest

  - name: Start Apache Server 
    service:
      name: httpd
      state: started 

  - name: Enable Apache Server
    service:
      name: httpd
      enabled: yes

  - name: Add Port 80/tcp in firewall
    firewalld:
      port: 80/tcp
      permanent: yes
      state: enabled

  - name: Add Port 80/udp in firewalld
    firewalld:
      port: 80/udp
      permanent: yes
      state: enabled

  - name: Add Port 8080/tcp in firewalld
    firewalld:
      port: 8080/tcp
      permanent: yes
      state: enabled

  - name: Add Port 8080/udp in firewalld
    firewalld:
      port: 8080/udp
      permanent: yes
      state: enabled

  - name: Reload service firewalld
    service:
      name: firewalld
      state: reloaded

  - name: Add HELLO WORLD!!! line to index.html file
    ansible.builtin.lineinfile:
      path: /var/www//html/index.html
      line: HELLO WORLD!!!
      create: yes

  - name: Restart Apache Server
    service:
      name: httpd
      state: restarted

