---
- name: mount module demo
  hosts: [ansible-server]
  gather_facts: yes
  become: true
  vars:
    mynfs: "192.168.1.14:/backup"
    mountpoint: "/nfs_share"
    permission: '0777'
    myopts: 'rw,sync,defaults,_netdev'
  tasks:
#    - name: utility present redhat-like
#      ansible.builtin.yum:
#        name:
#         - nfs-utils
#         - nfs4-acl-tools
#        state: present
#      when: ansible_os_family == 'CentOS'

#    - name: utility present debian-like
#      ansible.builtin.apt:
#        name:
#          - nfs-common
#          - nfs4-acl-tools
#        state: present
#      when: ansible_os_family == 'Debian'

    - name: check mountpoint exist
      ansible.builtin.file:
        path: "{{ mountpoint }}"
        state: directory
        mode: "{{ permission }}"
        owner: root
        group: root

    - name: mount network share
      ansible.posix.mount:
        src: "{{ mynfs }}"
        path: "{{ mountpoint }}"
        fstype: nfs
        opts: "{{ myopts }}"
        state: mounted

