---
- name: Install NFS-SERVER
  hosts: [testing1]
  gather_facts: no
  become_user: root
  tasks:
    - name: Update Epel-Release
      yum:
        name: epel-release
        state: present

    - name: Install REQUIRED PACKAGES
      yum:
        name: nfs-utils, nfs4-acl-tools
        state: latest

    - name: Start NFS Service
      service:
        name: nfs
        state: started

    - name: Enable NFS Service
      service:
        name: nfs
        enabled: yes

    - name: Add Port 2049/tcp in firewall
      firewalld:
        port: 2049/tcp
        permanent: yes
        state: enabled

    - name: Add Port 2049/udp in firewalld
      firewalld:
        port: 2049/udp
        permanent: yes
        state: enabled

    - name: Add Port 111/tcp in firewalld
      firewalld:
        port: 111/tcp
        permanent: yes
        state: enabled

    - name: Add Port 111/udp in firewalld
      firewalld:
        port: 111/udp
        permanent: yes
        state: enabled

    - name: Reload service firewalld
      service:
        name: firewalld
        state: reloaded

    - name: Change SELINUX mode to Permisive
      shell:
        cmd: setenforce 0
