---
- name: adding users with loops
  hosts: [testing1]
  vars:
    users:
      - user1
      - user2
      - user3
      - user4
  tasks:
    - name: Creating users by calling variables
      user:
        name: "{{ item }}"
        state: present
      loop: "{{ users }}"
...
