---
- hosts: all
  become_user: root
  tasks:
  - name: Installing the latest version of GIT (GLOBAL INFORMATION TRACKER)
    yum:
      name: git
      state: latest

  - name: Clone a PUBLIC repo
    ansible.builtin.git:
      repo: https://github.com/wajidarif/ansible-playbooks-repos
      dest: /root/GIT
      separate_git_dir: /root/GIT/repositories
      clone: yes
      update: yes
